# Role to work with basic components
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tenant-namespace
  name: tenant-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "persistentvolumeclaims", "secrets", "pods/log", "pods/portforward", "serviceaccounts", "endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["endpoints", "pods/binding"]
  verbs: ["get", "list", "watch", "update", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "update" , "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "update"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]

